
-- SELECT statement for Procedure
SELECT 
    resourcetype,
    id,
    meta_versionid,
    meta_lastupdated,
    meta_profile_0,
    extension_0_url,
    extension_0_valuereference_reference,
    extension_1_url,
    extension_1_valuereference_reference,
    extension_2_url,
    extension_2_valuereference_reference,
    status,
    code_coding_0_system,
    code_coding_0_code,
    code_coding_0_display,
    code_coding_1_system,
    code_coding_1_code,
    code_coding_1_display,
    code_coding_2_system,
    code_coding_2_code,
    code_coding_2_display,
    code_text,
    subject_reference,
    subject_display,
    performeddatetime,
    performer_0_actor_reference,
    performer_0_onbehalfof_reference,
    performer_1_actor_reference,
    performedperiod_start,
    performedperiod_end,
    note_0_text,
    category_coding_0_code,
    category_coding_0_display,
    category_coding_0_system,
    filename,
    processed_date 
FROM {{source('raw', 'procedure') }} x
QUALIFY rank() over(partition by filename order by processed_date desc) = 1
