
-- SELECT statement for Procedure_contained
SELECT 
    procedure_id,
    resourcetype,
    id,
    name_0_text,
    identifier_0_type_coding_0_system,
    identifier_0_type_coding_0_code,
    identifier_0_type_coding_0_display,
    identifier_0_type_text,
    identifier_0_system,
    identifier_0_value,
    identifier_1_system,
    identifier_1_value,
    name,
    name_0_family,
    name_0_given_0,
    name_0_given_1,
    telecom_0_system,
    telecom_0_value,
    telecom_0_use,
    telecom_1_system,
    telecom_1_value,
    telecom_1_use,
    address_0_use,
    address_0_text,
    address_0_line_0,
    address_0_city,
    address_0_state,
    address_0_postalcode,
    address_0_line_1,
    address_0_country,
    telecom_2_system,
    telecom_2_value,
    telecom_2_use,
    filename,
    processed_date 
FROM {{source('raw', 'procedure_contained') }} x
QUALIFY rank() over(partition by filename order by processed_date desc) = 1
