
-- SELECT statement for Observation_contained
SELECT 
    observation_id,
    resourcetype,
    id,
    identifier_0_system,
    identifier_0_value,
    name_0_family,
    name_0_given_0,
    name_0_given_1,
    name_0_text,
    name,
    partof_reference,
    partof_display,
    type_coding_0_display,
    collection_collecteddatetime,
    address_0_line_0,
    address_0_city,
    address_0_state,
    address_0_postalcode,
    contact_0_purpose_coding_0_system,
    contact_0_purpose_coding_0_code,
    contact_0_name_text,
    category_0_coding_0_system,
    category_0_coding_0_code,
    category_0_coding_0_display,
    code_coding_0_system,
    code_coding_0_code,
    code_coding_0_display,
    code_coding_1_system,
    code_coding_1_code,
    code_coding_1_display,
    subject_reference,
    subject_display,
    valuequantity_value,
    valuequantity_unit,
    valuequantity_system,
    valuequantity_code,
    note_0_text,
    filename,
    processed_date 
FROM {{source('raw', 'observation_contained') }} x
QUALIFY rank() over(partition by filename order by processed_date desc) = 1
