
-- SELECT statement for Encounter
SELECT 
    resourcetype,
    id,
    meta_versionid,
    meta_lastupdated,
    extension,
    identifier_0_system,
    identifier_0_value,
    identifier_0_assigner_display,
    class_system,
    class_code,
    class_display,
    status,
    type_0_coding_0_system,
    type_0_coding_0_code,
    type_0_coding_0_display,
    type_0_coding_1_system,
    type_0_coding_1_code,
    type_0_coding_1_display,
    type_0_coding_2_system,
    type_0_coding_2_code,
    type_0_coding_2_display,
    type_0_coding,
    type_0_text,
    subject_reference,
    subject_display,
    participant_0_type_0_coding_0_system,
    participant_0_type_0_coding_0_code,
    participant_0_type_0_coding_0_display,
    participant_0_type_0_text,
    participant_0_individual_reference,
    period_start,
    period_end,
    location_0_location_reference,
    location_0_location_display,
    diagnosis_0_condition_reference,
    diagnosis_0_use_coding_0_code,
    diagnosis_0_use_coding_0_display,
    diagnosis_0_use_coding_0_system,
    filename,
    processed_date 
FROM {{source('raw', 'encounter') }} x
QUALIFY rank() over(partition by filename order by processed_date desc) = 1
